name: Contentful Update Debounce

on:
  repository_dispatch:
    types: [contentful-update]

concurrency:
  group: contentful-debounce
  cancel-in-progress: true

jobs:
  debounce:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for additional updates
        run: sleep 60  # Wait 60 seconds for more updates
      
      - name: Trigger main build
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'azure-static-web-apps-purple-plant-0b6f92303.yml',
              ref: 'main'
            })